### ISSUE TITLE
Option to create project without any sample content.

### ISSUE THREAD

**Issue by gabrielwalt** [Adobe-Marketing-Cloud/aem-project-archetype#10]
There should be an option to create a project without any sample content, so that experienced developers don't have to start deleting things before getting started.

**Comment by jannae** [comment]
I have been looking into this. I'm pretty beginner with Maven, so any assistance or critique would be appreciated. From the link @steeleforge provided, it seems if you specify the modules to be built within the profiles instead of at the root level, you can control which ones maven builds for specific profiles.  

So after **commenting out the initial module declaration**, I modified the profiles section:

    <profiles>
        
        
        
        <profile>
            <id>adobe-public</id>

            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>

            <properties>
                <releaseRepository-Id>adobe-public-releases</releaseRepository-Id>
                <releaseRepository-Name>Adobe Public Releases</releaseRepository-Name>
                <releaseRepository-URL>http://repo.adobe.com/nexus/content/groups/public</releaseRepository-URL>
            </properties>

            <modules>
                <module>core</module>
                <module>ui.apps</module>
                <module>it.tests</module>
                <module>it.launcher</module>
            </modules>

            <repositories>
                <repository>
                    <id>adobe-public-releases</id>
                    <name>Adobe Public Repository</name>
                    <url>http://repo.adobe.com/nexus/content/groups/public</url>
                    <releases>
                        <enabled>true</enabled>
                        <updatePolicy>never</updatePolicy>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                </repository>
            </repositories>

            <pluginRepositories>
                <pluginRepository>
                    <id>adobe-public-releases</id>
                    <name>Adobe Public Repository</name>
                    <url>http://repo.adobe.com/nexus/content/groups/public</url>
                    <releases>
                        <enabled>true</enabled>
                        <updatePolicy>never</updatePolicy>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                </pluginRepository>
            </pluginRepositories>
        </profile>

        <profile>
            <id>sample-content</id>
            
            <properties>
                <releaseRepository-Id>adobe-public-releases</releaseRepository-Id>
                <releaseRepository-Name>Adobe Public Releases</releaseRepository-Name>
                <releaseRepository-URL>http://repo.adobe.com/nexus/content/groups/public</releaseRepository-URL>
            </properties>
            
            <modules>
                <module>core</module>
                <module>ui.apps</module>
                <module>ui.content</module>
                <module>it.tests</module>
                <module>it.launcher</module>
            </modules>
            
            <repositories>
                <repository>
                    <id>adobe-public-releases</id>
                    <name>Adobe Public Repository</name>
                    <url>http://repo.adobe.com/nexus/content/groups/public</url>
                    <releases>
                        <enabled>true</enabled>
                        <updatePolicy>never</updatePolicy>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                </repository>
            </repositories>

            <pluginRepositories>
                <pluginRepository>
                    <id>adobe-public-releases</id>
                    <name>Adobe Public Repository</name>
                    <url>http://repo.adobe.com/nexus/content/groups/public</url>
                    <releases>
                        <enabled>true</enabled>
                        <updatePolicy>never</updatePolicy>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                </pluginRepository>
            </pluginRepositories>
        </profile>
    </profiles>

Now when I build with the default profile, it includes everything except ui.content, and or when I build using `mvn clean install -Psample-content` it does indeed *try* to build ui.content. 

This solution does strike me as rather messy, as it has quite a lot of repetition, but that is probably just my ignorance about maven. 

Thoughts? If this is actually the way to do this, I'm happy to do a pul request. It does work, as gross as it may be.

**Comment by rombert** [comment]
@jannae - would be great if you could submit a pull request. One comment is that profiles in Maven are additive. You only need to add the new stuff, e.g. the ui.content module ; everything else can be removed.

**Comment by gabrielwalt** [comment]
Also, we should provide an option to pick which projects it should create (core, apps, content, it).

**Comment by bpauli** [comment]
With Maven 3.2.1 you can also use the `-pl` command line option to exclude modules from a reactor project as created by this archetype.

For example to skip the installation of the sample content you can execute 
`mvn clean install -PautoInstallPackage -pl !ui.content`

Note: As the `!` character has a special meaning on bash or zsh you have to escape it with `\`. In this case the command is ` mvn clean install -PautoInstallPackage -pl \!ui.content `
