### ISSUE TITLE
UI.apps not building with core.wcm.components.all dependency on 1.0.6

### ISSUE THREAD

**Issue by marijnvermeulen-adobe** [Adobe-Marketing-Cloud/aem-project-archetype#106]
I got the following error when trying to build Archetype 12. 

> [ERROR] Failed to execute goal on project bpce.ui.apps: Could not resolve dependencies for project com.adobe.aem:bpce.ui.apps:content-package:1.0-SNAPSHOT: Failure to find com.adobe.cq:core.wcm.components.all:zip:1.0.6 in https://artifactory.corp.adobe.com/artifactory/maven-aem-dev was cached in the local repository, resolution will not be reattempted until the update interval of artifactory-releases has elapsed or updates are forced -> [Help 1]

When I updated this dependency to 1.1.0, the issue was resolved. 
 
```
           <dependency>
                <groupId>com.adobe.cq</groupId>
                <artifactId>core.wcm.components.all</artifactId>
                <type>zip</type>
                <version>1.0.6</version>
            </dependency>
```

**Comment by bpauli** [comment]
@marijnvermeulen-adobe, you're using a different repo in your maven configuration. com.adobe.cq:core.wcm.components.all:zip:1.0.6 is only available on the public maven repository https://repo.adobe.com/. Please check your local maven settings ~/.m2/settings.xml or build the project with the adobe-public maven profile (e.g. mvn -P adobe-public clean install).

**Comment by marijnvermeulen-adobe** [comment]
Makes perfect sense, wasn't aware of that. Thank you for the clarification!
