### ISSUE TITLE
Leverage new Jackrabbit Filevault Maven Plugin for building packages

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/aem-project-archetype#108]
Using the new FileVault plugin (http://jackrabbit.apache.org/filevault-package-maven-plugin/index.html) for creating packages has the following advantages:

- Copying things from src to target is no longer necessary (https://issues.apache.org/jira/browse/JCRVLT-210 and https://issues.apache.org/jira/browse/JCRVLT-230)
- Building packages with the Adobe plugin is no longer supported since v 1.0.2

The Adobe plugin is still necessary for deployment though, compare with http://jackrabbit.apache.org/filevault-package-maven-plugin/migrating.html.

**Comment by jakegarelick** [comment]
I can pick this up, but I have a question - how do I do this in content-package-maven-plugin 1.0.2?
```<embeddeds>
                        <embedded>
                            <groupId>com.adobe.training</groupId>
                            <artifactId>training-project.core</artifactId>
                            <target>/apps/training-project/install</target>
                        </embedded>
                    </embeddeds>
                    <subPackages>
                        <subPackage>
                            <groupId>com.adobe.cq</groupId>
                            <artifactId>core.wcm.components.all</artifactId>
                            <filter>true</filter>
                        </subPackage>
                    </subPackages>```

**Comment by gabrielwalt** [comment]
Thanks @kwin, you're right, we'll update that!

**Comment by kwin** [comment]
The fix is only covering some aspects. To benefit from the performance improvement one should no longer copy from `src` to `target`. Can you remove the according resource section from all package modules?

**Comment by bpauli** [comment]
@kwin Can you please review my latest PR https://github.com/Adobe-Marketing-Cloud/aem-project-archetype/pull/150? Thanks!

**Comment by kwin** [comment]
LGTM
