### ISSUE TITLE
Archetype 12: autoInstallPackage does not install/update the bundle

### ISSUE THREAD

**Issue by priyankp3005** [Adobe-Marketing-Cloud/aem-project-archetype#114]
I am unable to install/update the bundle using the command : mvn clean install -PautoInstallPackage. 

I am using : 
1. AEM 6.3 SP1 with AEM Forms 6.3 SP1 Add-on. 
2. Eclipse Oxygen (4.7.2)
3. AEM developer tools (1.1) + Sling IDE Tool 1.2

Steps: 
1. Create AEM project using Maven Archetype 12. 
2. Updated uber.jar dependency to use version 6.3.1.
3. Run mvn clean install -PautoInstallPackage. It install the package and the bundle first time successfully. 
    Note: I do see some white listing errors when it install the package. 
4.  Change some component code from crx/de. And then import the content using the AEM Developer Tool for Eclipse.
5. Make additional component code change in ui.apps project. 
6. Update code in the core project (update any java class). 
7. Run mvn clean install -PautoInstallPackage. 
8. No error reported. But I only see component code updates. Bundle is not updated. I checked the bundle in /system/console/bundles. Timestamp for bundle modification is not updated. 
9. But if I use mvn install -PautoInstallBundle command. It deploys the bundle just fine. 

Additional Notes: 
If I create a project using the traditional Archetype 10 (for AEM 6.2), I don't see this issue.  But it still uses the maven-scr-plugin and scr annotations. I would prefer to use the latest archetype for my 6.3 project.

**Comment by gabrielwalt** [comment]
Hi @priyankp3005, meanwhile could you find a solution to this problem?

**Comment by priyankp3005** [comment]
Yes. I started using lazybones and that is working as expected..

**Comment by bpauli** [comment]
I was not able to reproduce the issue with the latest archetype version and AEM 6.4.
