### ISSUE TITLE
CSS files missing in the archetype 12 and 13  

### ISSUE THREAD

**Issue by artika4biz** [Adobe-Marketing-Cloud/aem-project-archetype#119]
In archetype 12 and 13, referenced css are missing: 

27.07.2018 11:07:28.818 *WARN* [0:0:0:0:0:0:0:1 [1532682440380] GET /libs/granite/core/content/login.html HTTP/1.1] com.adobe.granite.ui.clientlibs.impl.FileBundle Referenced path in /apps/aem63training/components/content/breadcrumb/clientlib/css.txt does not exist: /apps/aem63training/components/content/breadcrumb/clientlib/less/breadcrumb.css

**Comment by bpauli** [comment]
@artika4biz Thank you for the hands up!
