### ISSUE TITLE
404 Custom error handler

### ISSUE THREAD

**Issue by artika4biz** [Adobe-Marketing-Cloud/aem-project-archetype#121]
I would remove it from the archetype definition because this is a per server configuration and not a per project customization: if two people of the same team are working on different projects and they started their work from this archetype, they could think that every one is working on "his own" 404 error handler.

I would propose to create a new, per AEM instance, archetype with all best practices and ideas, like the 404 error handler valid for a whole AEM instance, not for a single project: does it make sense?

**Comment by bpauli** [comment]
@artika4biz, Thank you for bringing up this idea. We will take care of it.

CQ-4250956
