### ISSUE TITLE
Error while running autoinstall package in maven

### ISSUE THREAD

**Issue by ritikrajambastha** [Adobe-Marketing-Cloud/aem-project-archetype#126]
While running mvn clean install -PautoInstallPackage, I am getting error that Mockito cannot mock this class: interface org.apache.sling.settings.SlingSettingsService.Please suggest

-------------------------------------------------------------------------------
Test set: com.aem.demo.core.models.TestHelloWorldModel
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.206 s <<< FAILURE! - in com.aem.demo.core.models.TestHelloWorldModel
testGetMessage(com.aem.demo.core.models.TestHelloWorldModel)  Time elapsed: 1.07 s  <<< ERROR!
org.mockito.exceptions.base.MockitoException: 

Mockito cannot mock this class: interface org.apache.sling.settings.SlingSettingsService.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.

Java               : 10
JVM vendor name    : "Oracle Corporation"
JVM vendor version : 10.0.2+13
JVM name           : Java HotSpot(TM) 64-Bit Server VM
JVM version        : 10.0.2+13
JVM info           : mixed mode
OS name            : Mac OS X
OS version         : 10.14

Underlying exception : java.lang.UnsupportedOperationException: Cannot define class using reflection
	at com.aem.demo.core.models.TestHelloWorldModel.setup(TestHelloWorldModel.java:43)
Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection
	at com.aem.demo.core.models.TestHelloWorldModel.setup(TestHelloWorldModel.java:43)
Caused by: java.lang.IllegalArgumentException: Unknown Java version: 10
	at com.aem.demo.core.models.TestHelloWorldModel.setup(TestHelloWorldModel.java:43)

**Comment by gabrielwalt** [comment]
Assuming this was more of a question about whether we support Java 10, which got answered, therefore closing the issue. If you have further questions or issues with that, please reopen.
