### ISSUE TITLE
Stray JSP Tag in Sightly Page Template

### ISSUE THREAD

**Issue by cyface** [Adobe-Marketing-Cloud/aem-project-archetype#13]
In the file aem-project-archetype/src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/page/page/page.html

There is still a JSP tag in there: `<meta http-equiv="keywords" content="<%= WCMUtils.getKeywords(currentPage) %>">`

I'm honestly not sure how to grab the keywords using Sightly, so I'm curious to see what the Sightly way of doing that is! :)

**Comment by rombert** [comment]
Thanks for the report! I've removed the JSP scriptlet, but for now I didn't add the keywords back using Sightly. That would best be done with a use object
