### ISSUE TITLE
Image component is missing supportedMimeTypes configuration

### ISSUE THREAD

**Issue by msagolj** [Adobe-Marketing-Cloud/aem-project-archetype#132]
In:

https://github.com/Adobe-Marketing-Cloud/aem-project-archetype/blob/master/src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/image/_cq_editConfig.xml

we should add a supportedMimeType configuration, to make sure that GIF and SVG upload are not showing image transformation tools for editing.

**Comment by bpauli** [comment]
configuration for cropping is still missing
