### ISSUE TITLE
default dispatcher configuration

### ISSUE THREAD

**Issue by reusr1** [Adobe-Marketing-Cloud/aem-project-archetype#134]
it would be great if the archetype provides a default dispatcher configuration for author and publish dispatcher that can be used as a start to automate dispatcher configurations

**Comment by andreeadracea** [comment]
I've created an internal issue for this enhancement. 
(CQ-4259370)

**Comment by gabrielwalt** [comment]
As it seems, this is something that will rather be provided (or already is provided) by the future Cloud Manager default setup, rather than by the Core Components.
