### ISSUE TITLE
target dns management

### ISSUE THREAD

**Issue by reusr1** [Adobe-Marketing-Cloud/aem-project-archetype#135]
the archetype should allow for a target dns name and set up the related configurations for AEM accordingly

**Comment by andreeadracea** [comment]
@reusr1 , I've created an internal issue for this enhancement and based on out bandwidth will we take care of it. 
(CQ-4259369)

**Comment by gabrielwalt** [comment]
Unfortunately, I don't think that we can realistically deliver this in the next 6 months. Therefore, I'm closing this issue for now. But if you have the possibility to contribute on this, which we'd encourage, then please reopen the ticket to further discuss the topic.
