### ISSUE TITLE
logger configured in archetype project

### ISSUE THREAD

**Issue by lbaoyu** [Adobe-Marketing-Cloud/aem-project-archetype#14]
I created a new project with archetype 7, and find out I cannot find any output in error.log.
After investigation we find a dedicated logger is created for the log, and its log level is set to Error. 

I have three suggestions here: 
(1) the logger level is better to be Info or debug. Error is normally only used for project live env.
(2) In my case I only need back end coding for the project. but there is no specific archetype for it, so that I have to create the project with one available archetype and remove stuff not being used.
(3) sample-project-archetype 5, 6 or 7 is hard for users to tell the distinctions between them.

**Comment by rombert** [comment]
All of those are valid points, thanks for reporting.

When performing releases we'll also generate changelogs so that users will know what has changed.

**Comment by gabrielwalt** [comment]
(1) I've increased the level of the logger to info. As a result I also removed config.dev.
(2) That's a great suggestion, we'll try to see if we can provide something that goes into that direction in the future.
(3) As @rombert said, we'll create change logs in the future.
