### ISSUE TITLE
/content/$(site)/jcr:content is set to nt:unstructured

### ISSUE THREAD

**Issue by rombert** [Adobe-Marketing-Cloud/aem-project-archetype#143]
Looks like the /content/$(site)/jcr:content node is set to `nt:unstructured` . Shouldn't this be `cq:PageContent` instead?

https://github.com/Adobe-Marketing-Cloud/aem-project-archetype/blob/a7983b8104621ec97aab7f338ecd60fc1df2962d/src/main/archetype/ui.content/src/main/content/jcr_root/content/__contentFolderName__/.content.xml#L4-L16

**Comment by bpauli** [comment]
@rombert Thanks you for reporting this issue
