### ISSUE TITLE
Set allowIndexDefinitions to 'true' for Jackrabbit Filevault plugin

### ISSUE THREAD

**Issue by jbharrell** [Adobe-Marketing-Cloud/aem-project-archetype#145]
Should the new filevault configuration have allowIndexDefinitions=true ?  ACS Commons includes index definitions and this is likely one of the most common use cases.

https://github.com/Adobe-Marketing-Cloud/aem-project-archetype/blob/8e340467eef50f9b2b7128da43a5f5c88f8d3a35/src/main/archetype/ui.content/pom.xml#L91

**Comment by jbharrell** [comment]
Assuming this is a valid request, feel free to assign to me.  I've got the fix fresh in my mind from addressing it today in a project.

**Comment by joerghoh** [comment]
I am not too big a fan of deploying index definitions directly to /oak:index; it's way to easy to purge an index during a deployment or cause a reindex of it although it has not changed(either by wrong packaging or by accident).
I would recommend to use EnsureOakIndex of ACS AEM Commons instead.

**Comment by jbharrell** [comment]
@joerghoh Thanks for the feedback!  

Let me clarify, adding ACS Commons to a project using a subpackage in the filevalut packager ([as described here](https://adobe-consulting-services.github.io/acs-aem-commons/pages/maven.html)) is causing the build to fail when `allowIndexDefinitions=false`.  I think this is due to the `/oak:index` in ACS Commons ([here](https://github.com/Adobe-Consulting-Services/acs-aem-commons/tree/master/content/src/main/content/jcr_root/_oak_index)).  But based on your comment, I wonder if this should be a issue in ACS Commons vs here?  Or maybe there is something that I should be doing different in the including POM?  What do you think?

**Comment by bpauli** [comment]
@jbharrell I agree, this should be more an issue for ACS Commons. At least it should be documented n the page you already linked at [1].

As we don't include the ACS commons OOTB in the maven archetype I will close this issue. It would be nice if you can open an issue on the ACS commons repo for this. Thanks!

[1] https://adobe-consulting-services.github.io/acs-aem-commons/pages/maven.html

**Comment by justinedelson** [comment]
ACS AEM Commons does not include any indexes. If the error message says that it does, this is a false positive and needs to be fixed IMO.

**Comment by kwin** [comment]
This is tracked now in https://issues.apache.org/jira/browse/JCRVLT-343.
