### ISSUE TITLE
Integration of Component Library examples content package

### ISSUE THREAD

**Issue by bpauli** [Adobe-Marketing-Cloud/aem-project-archetype#148]
The next release of the core components will contain an example content package with the component  library [1]. It would be helpful for a new aem project setup to include this example content package in the archetype as well.

[1] http://opensource.adobe.com/aem-core-wcm-components/library.html

**Comment by bpauli** [comment]
@godanny86 Thank you, for your feedback. I added a new parameter `optionIncludeExample` in the latest commit
https://github.com/Adobe-Marketing-Cloud/aem-project-archetype/pull/149/commits/44926a327e473377945825edc28022478015954d

**Comment by godanny86** [comment]
awesome!
