### ISSUE TITLE
Adding support for @Inject (sling-models)

### ISSUE THREAD

**Issue by heervisscher** [Adobe-Marketing-Cloud/aem-project-archetype#19]
Currently it is not possible to use Inject within a sling-models class, because the sling-model dependency is missing.

**Comment by steeleforge** [comment]
archetype need also include this in the bundle manifest <Sling-Model-Packages>{...namespace...}</Sling-Model-Packages>

**Comment by steeleforge** [comment]
https://github.com/Adobe-Marketing-Cloud/aem-project-archetype/pull/27
