### ISSUE TITLE
semantic versioning defaultValue

### ISSUE THREAD

**Issue by steeleforge** [Adobe-Marketing-Cloud/aem-project-archetype#22]
The default value of ${version} might be better served for users if it defaulted to a semver[1] heuristic.
#### archetype-metadata.xml

```
    <requiredProperty key="version">
        <defaultValue>0.1.0-SNAPSHOT</defaultValue>
    </requiredProperty>
```

[1]http://semver.org/

**Comment by gabrielwalt** [comment]
Thanks!

**Comment by gabrielwalt** [comment]
This actually makes that the archetype cannot be used anymore with the wizard of the Eclipse extension. I've reverted that for now.

**Comment by steeleforge** [comment]
drat. I didn't even consider the wizard eclipse. What a bizarre edge case. I don't see anything in the userland about why this might cause an issue with eclipse.

**Comment by rombert** [comment]
Reopening since this was reverted

**Comment by bpauli** [comment]
I don't see currently a way to change the default version to the semantic versioning for the following reasons:
1. It's currently not supported by the eclipse project wizard (as mentioned above).
2. When the property is provided in the metadata of the archetype it's not possible to enter a different value in interactive mode.
