### ISSUE TITLE
Local build instructions in README.MD

### ISSUE THREAD

**Issue by steeleforge** [Adobe-Marketing-Cloud/aem-project-archetype#23]
local installation instructions would help developers use the pre-release versions of this archetype

### Building
To compile and use an edge, local version of this archetype:

    mvn clean install archetype:update-local-catalog
    
    mvn archetype:generate \
     -DarchetypeCatalog=local
     -DarchetypeGroupId=com.adobe.granite.archetypes \
     -DarchetypeArtifactId=aem-project-archetype \
     -DarchetypeVersion=9-SNAPSHOT.

**Comment by gabrielwalt** [comment]
Thanks!
