### ISSUE TITLE
SlingQuery extension?

### ISSUE THREAD

**Issue by steeleforge** [Adobe-Marketing-Cloud/aem-project-archetype#28]
This might be a worthwhile addition to the archetype core pom https://github.com/apache/sling/tree/trunk/contrib/extensions/sling-query

**Comment by rombert** [comment]
I think that for now we should stick to bundles that are already availble in the product. Once/if SlingQuery is in, we can add it to the archetype

**Comment by bpauli** [comment]
SlingQuery will never be shipped directly with the AEM as it is an (useful) SLING extension. Therefore we decided to not include it directly in the AEM archetype.

If you want include the SlingQuery together with your archetype generated project you have to follow this steps manually:
1.: Add the dependency to your reactor pom.xml
```xml
<dependencies>
....
  <dependency>
    <groupId>org.apache.sling</groupId>
    <artifactId>org.apache.sling.query</artifactId>
    <version>3.0.0</version>
    <scope>provided</scope>
  </dependency>
...
</dependencies>
```
2.: To make use of the SlingQuery API add the dependency also to the core/pom.xml
```xml
<dependencies>
....
  <dependency>
    <groupId>org.apache.sling</groupId>
    <artifactId>org.apache.sling.query</artifactId>
  </dependency>
...
</dependencies>
```
3.: And finally, in case you want to auto install the bundle together with the ui.apps content-package, you have to add the dependency in ui.apps/pom.xml as well (see step 2) additionally to the embedded section of the `content-package-maven-plugin`
```xml
<plugin>
  <groupId>com.day.jcr.vault</groupId>
  <artifactId>content-package-maven-plugin</artifactId>
    ....
  <configuration>
    ...
    <embeddeds>
       ...
      <embedded>
        <groupId>org.apache.sling</groupId>
        <artifactId>org.apache.sling.query</artifactId>
        <target>/apps/<appsFolderName>/install</target>
       </embedded>
       ...
   </embeddeds>
   ...
  <configuration>
</plugin>
```

Please, make sure to replace `<appsFolderName>` with the proper appsFolderName property provided at the archetype generation.
