### ISSUE TITLE
Provide dependencies for AEM 6.1

### ISSUE THREAD

**Issue by kwin** [Adobe-Marketing-Cloud/aem-project-archetype#36]
In AEM 6.1 the dependencies JAR moved from 

```
<dependency>
    <groupId>com.adobe.aem</groupId>
    <artifactId>aem-api</artifactId>
    <version>6.0.0.1</version>
</dependency>
```

to 

```
<dependency>
    <groupId>com.day.cq</groupId>
    <artifactId>cq-quickstart</artifactId>
    <version>6.1.0</version>
    <classifier>apis</classifier>
</dependency>
```

**Comment by gabrielwalt** [comment]
Great point!
Thanks, I'll add this when we'll make a general update for 6.1, which should also include the config for the responsive grid.

**Comment by kwin** [comment]
Currently the given 6.1 dependency has the drawback that there are no method bodies in there (leading to problems when using those classes during tests and also when using together with the maven-scr-plugin, because that one is using classcode analysis to a certain extent also on dependencies which fails due to the missing method bodies).

**Comment by gabrielwalt** [comment]
Also make sure to check this out:
https://github.com/justinedelson/aem-uberjar-demo

**Comment by toniedzwiedz** [comment]
It would be nice to upgrade it to use the AEM 6.2 API at this point. As far as I can see, version 11-SNAPSHOT is still using the 6.0.0.1 dependency.

**Comment by toniedzwiedz** [comment]
Ah, just noticed https://github.com/Adobe-Marketing-Cloud/aem-project-archetype/pull/64

**Comment by rombert** [comment]
Already done via #64
