### ISSUE TITLE
Running integration tests fails: Expecting HelloWorldModel to be injected by Sling test runner

### ISSUE THREAD

**Issue by rombert** [Adobe-Marketing-Cloud/aem-project-archetype#38]
- Generate a project from version 10 of the archetype
- Start a CQ 6.0 instance
- Run `mvn clean verify -PintegrationTests`

Result

> Results :
> 
> Failed tests: 
>   SlingServerSideTest.testHelloWorldModelServerSide testHelloWorldModelServerSide(com.example.it.tests.HelloWorldModelServerSideTest): Expecting HelloWorldModel to be injected by Sling test runner
> 
> Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

**Comment by MuriloDAG** [comment]
Is there an ETA for this bug? Thanks
