### ISSUE TITLE
Replace column control component with responsive grid usage

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Marketing-Cloud/aem-project-archetype#45]
Since AEM 6.1, there's no reason (IMHO) to have a custom column control component. Instead, the page component should be using the responsive grid.

**Comment by gabrielwalt** [comment]
+1

**Comment by rombert** [comment]
When do we move to AEM 6.1 exclusively?

**Comment by bpauli** [comment]
fixed in #103
