### ISSUE TITLE
currentPage.template never works on publish

### ISSUE THREAD

**Issue by heervisscher** [Adobe-Marketing-Cloud/aem-project-archetype#52]
In the page.html we have:

${currentPage.template.name}

This will always result into an error on publish, because getTemplate() returns null on publish.

**Comment by joemaffia** [comment]
```
${pageProperties.cq:template}
```
should do... although you get back the path and not the name

**Comment by heervisscher** [comment]
To me the getTemplate() can better be deprecated.
cq:template indeed gives the full path, so that needs to be stripped somehow
