### ISSUE TITLE
Integration Tests execute twice

### ISSUE THREAD

**Issue by shsteimer** [Adobe-Marketing-Cloud/aem-project-archetype#53]
When running `mvn clean install -PautoInstallPackage,integrationTests` I see the following output in the maven log, and it appears the integration tests are executing twice.

```
2421 [main] INFO org.apache.sling.junit.remote.httpclient.RemoteTestHttpClient - Executing test remotely, path=/com.test.it.tests.json JUnit servlet URL=http://localhost:4502/test/sling/1446666680947.junit
2437 [main] INFO org.apache.sling.junit.remote.testrunner.SlingRemoteTestRunner - Server-side tests executed as admin at http://localhost:4502/test/sling/1446666680947.junit with path /com.test.it.tests.json
Running com.test.it.launcher.SlingServerSideTest
2440 [main] INFO org.apache.sling.junit.remote.httpclient.RemoteTestHttpClient - Executing test remotely, path=/com.test.it.tests.json JUnit servlet URL=http://localhost:4502/test/sling/1446666680947.junit
2454 [main] INFO org.apache.sling.junit.remote.testrunner.SlingRemoteTestRunner - Server-side tests executed as admin at http://localhost:4502/test/sling/1446666680947.junit with path /com.test.it.tests.json
```

This can be verified by attaching a remote debugger and setting a breakpoint in the test class.

**Comment by rombert** [comment]
At this point I'm not sure why this happens. I can see that there are two instances of `org.apache.sling.junit.remote.testrunner.SlingRemoteTestRunner` being referenced by the JUnit runners, but I am not sure why.

The stack traces of the executions are below and it looks like we execute the tests way too early then the suite description is being generated. Maybe it's a strange interaction between our test runners and the maven-failsafe-plugin ... I'll put this on hold for now until I or someone else has a better idea.

    Thread [main] (Suspended (entry into method maybeExecuteTests in SlingRemoteTestRunner))	
	SlingRemoteTestRunner.maybeExecuteTests() line: 90	
	SlingRemoteTestRunner.getChildren() line: 138	
	SlingRemoteTestRunner(ParentRunner<T>).getFilteredChildren() line: 276	
	SlingRemoteTestRunner(ParentRunner<T>).getDescription() line: 225	
	Suite.describeChild(Runner) line: 123	
	Suite.describeChild(Object) line: 24	
	Suite(ParentRunner<T>).getDescription() line: 226	
	JUnit4ProviderUtil.createSuiteDescription(Collection<Class<?>>) line: 113	
	JUnit4Provider.createTestsDescription() line: 257	
	JUnit4Provider.invoke(Object) line: 124	
	ForkedBooter.invokeProviderInSameClassLoader(Object, Object, ProviderConfiguration, boolean, StartupConfiguration, boolean) line: 203	
	ForkedBooter.runSuitesInProcess(Object, StartupConfiguration, ProviderConfiguration, PrintStream) line: 155	
	ForkedBooter.main(String[]) line: 103


    Thread [main] (Suspended (entry into method maybeExecuteTests in SlingRemoteTestRunner))	
	SlingRemoteTestRunner.maybeExecuteTests() line: 90	
	SlingRemoteTestRunner.getChildren() line: 138	
	SlingRemoteTestRunner(ParentRunner<T>).getFilteredChildren() line: 276	
	SlingRemoteTestRunner(ParentRunner<T>).getDescription() line: 225	
	SlingRemoteTestRunner(ParentRunner<T>).run(RunNotifier) line: 232	
	JUnit4Provider.execute(Class<?>, RunNotifier, String[]) line: 283	
	JUnit4Provider.executeWithRerun(Class<?>, RunNotifier, String[]) line: 173	
	JUnit4Provider.executeTestSet(Class<?>, RunListener, RunNotifier) line: 153	
	JUnit4Provider.invoke(Object) line: 128	
	ForkedBooter.invokeProviderInSameClassLoader(Object, Object, ProviderConfiguration, boolean, StartupConfiguration, boolean) line: 203	
	ForkedBooter.runSuitesInProcess(Object, StartupConfiguration, ProviderConfiguration, PrintStream) line: 155	
	ForkedBooter.main(String[]) line: 103
