### ISSUE TITLE
Installing bundle fails due to PUT method

### ISSUE THREAD

**Issue by jfrantzius** [Adobe-Marketing-Cloud/aem-project-archetype#56]
Hi,

when using the archetype out-of-the-box, it is impossible to install the core bundle into a running AEM server using the maven-sling-plugin:

```
$ mvn -PautoInstallBundle sling:install
[..]
[INFO] Installing Bundle com.aperto.aem-example.core(/Users/joerg.frantzius/eclipse-workspaces/aem-training/aem-example/core/target/aem-example.core-0.0.1-SNAPSHOT.jar) to http://localhost:4502/crx/repository/crx.default/apps/aemexample/install/ via PUT
[..]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[..]
[ERROR] Failed to execute goal org.apache.sling:maven-sling-plugin:2.1.0:install (default-cli) on project aem-example.core: Installation on http://localhost:4502/crx/repository/crx.default/apps/aemexample/install/ failed, cause: Installation failed, cause: Method Not Allowed -> [Help 1]
```

When I change the maven-sling-plugin configuration to `<usePut>false</usePut>`, then the bundle install works as expected.

Maybe that's a bug either in the maven-sling-plugin implementation or documentation, as its [documentation](http://sling.apache.org/site/sling.html#Sling-install) says that usePut is false by default.

**Comment by dzmitry-kankalovich** [comment]
Same problem here with exception that neither PUT nor POST works for me. Started to notice this issue for AEM 6.1

**Comment by mskalicky** [comment]
I am having the same problem with 6.1 but only on publish.  Author seems to work fine.  Have either of you found a solution?

**Comment by jfrantzius** [comment]
@mskalicky please see the issue description:
> When I change the maven-sling-plugin configuration to <usePut>false</usePut>, then the bundle install works as expected.

**Comment by mskalicky** [comment]
Can I ask what you're using for your slingUrl and slingUrlSuffix?

**Comment by kwin** [comment]
Please use the latest version of maven-sling-plugin and check the 'deploymentMethod' parameter.

**Comment by rombert** [comment]
I've changed the default to use the web console for deployment. Note that as @kwin mentioned, you can always change it to something else that suits your deployment scenario.
