### ISSUE TITLE
Failed publishing "Item is protected" using New MultiModule Project wizard

### ISSUE THREAD

**Issue by liujason** [Adobe-Marketing-Cloud/aem-project-archetype#58]
I tried using the new project wizard and created the aem-project-archetype-10 project and deploy to a quickstart, and saw the following error message during publish.

Failed publishing path=/, result=JcrResult[ success:false, exception: org.apache.sling.ide.transport.RepositoryException - javax.jcr.nodetype.ConstraintViolationException: Item is protected]

**Comment by rombert** [comment]
What version of the IDE tooling are you using? Did you make any changes to the generated project?

**Comment by liujason** [comment]
Hi @rombert , I'm using Eclipse Mars.1 Release (4.5.1) with AEM developer tools (1.0.6), Sling IDE Tools (1.0.10). Maven (3.2.5). Java (1.8.0_73). 

Thanks!

Jason

**Comment by rombert** [comment]
I can't reproduce this at my end and I am not sure why the Eclipse plugin would try to update the root node. Can you attach/paste your filter.xml files and also the settings that you used when creating the project?

**Comment by bpauli** [comment]
Closed, as request for more informations was not answered.
