### ISSUE TITLE
Core bundle does not resolve on AEM 6.2 due to different version of javax.inject

### ISSUE THREAD

**Issue by rombert** [Adobe-Marketing-Cloud/aem-project-archetype#59]
With AEM 6.2 the javax.inject package is exported with version 1.0.0 by `org.apache.geronimo.specs.geronimo-atinject_1.0_spec`. Before that it was exported with version `0.0.0`, and the core bundle ( when compiled ) creates an import range of `[0,1)`

<img width="1259" alt="javaxinjectmissing" src="https://cloud.githubusercontent.com/assets/21237/14107983/be1a42ee-f5c3-11e5-958e-0c223f873cdb.png">

**Comment by bertoltmeier** [comment]
Hi.

I tried out the fix in my local POM, which was created from the archetype for an AEM6.1 project, but the fix would not work.

I had to add the following dependencies to the core/pom.xml to make javax.inject work: 


        <dependency>
            <groupId>org.apache.geronimo.specs</groupId>
            <artifactId>geronimo-atinject_1.0_spec</artifactId>
            <version>1.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.inject</groupId>
            <artifactId>javax.inject</artifactId>
            <version>1</version>
        </dependency>

**Comment by pepe79** [comment]
The fixing commit e8239a9 fixes also the same problem in AEM 6.1 after installing the Service Pack 2 .

**Comment by ksurendra** [comment]
The same also shows up on AEM 6.3

and adding the dependencies does not fix the issue.

**Comment by vaibhavvasa236** [comment]
This issue is mainly due to version mismatch.
Add the following package import inside "<configuration>/<instructions> in pom.xml of your project's core. 
<Import-Package>
							javax.inject;version=0.0.0,com.day.cq.replication;version="[6.0.0,7)",
							org.apache.sling.event.jobs;version="[1.5,2]",
							com.day.cq.workflow;version="[1.0,2)",
							com.day.cq.workflow.exec;version="[1.0,2)",
							com.day.cq.workflow.metadata;version="[1.0,2)",
							org.apache.sling.models.annotations;version="[1.1,2)",
							com.day.cq.commons.jcr;version="[5.7.0,7.0.0)",
							*
</Import-Package>
It should work then

**Comment by somanath11** [comment]
Thanks @vaibhavvasa236 it worked for me.

**Comment by SahilAhmedSheikh** [comment]
hello @vaibhavvasa236,

I m using AEM 6.2.0. 
I have created a simple custom text component , but when i create java file for the same and using @Model the following error "package org.apache.sling.models.annotations does not exist
[ERROR] symbol: class Model"
  to resolve the same i have included the external jar "org.apache.sling.models.api-1.3.8" into my project as well. i m using Intelij. Could u help me resolving the  issue.

Regards
Sahil
