### ISSUE TITLE
outputDirectory in configuration doesn't validate

### ISSUE THREAD

**Issue by tlwhit2** [Adobe-Marketing-Cloud/aem-project-archetype#61]
The 'outputDirectory' configuration for the Felix SCR plugin throws a 'element not allowed here' error in the POM editors; I'm wondering if we need to include an additional namespace?

				<plugin>
					<groupId>org.apache.felix</groupId>
					<artifactId>maven-scr-plugin</artifactId>
					<version>1.20.0</version>
					<executions>
						<execution>
							<id>generate-scr-scrdescriptor</id>
							<goals>
								<goal>scr</goal>
							</goals>
							<configuration>
								
								<properties>
									<service.vendor>Adobe</service.vendor>
								</properties>
							</configuration>
						</execution>
					</executions>
					<configuration>
						<outputDirectory>${project.build.directory}/classes</outputDirectory>
					</configuration>
					<dependencies>
						<dependency>
							<groupId>org.slf4j</groupId>
							<artifactId>slf4j-simple</artifactId>
							<version>1.5.11</version>
						</dependency>
					</dependencies>
				</plugin>

**Comment by rombert** [comment]
There is no error for me, and the property is documented at http://felix.apache.org/documentation/subprojects/apache-felix-maven-scr-plugin/apache-felix-maven-scr-plugin-use.html .

What is the exact error that is reported? Also, what versions of Eclipse and m2e are you using?

**Comment by tlwhit2** [comment]
I was seeing the error in IntelliJ using Maven 3.3.9.  I just updated to version 1.21.0 of the plugin, everything seems fine...I'll close this issue. Thanks!

**Comment by dmitriiivashko** [comment]
Having the same issue with 1.20.0 and 1.22.0 (works with 1.21.0)

**Comment by HitmanInWis** [comment]
Switching to 1.21.0 did not fix the issue for me.  Looking at the plugin.xml for maven-scr-plugin, the outputDirectory config looks like this:

`
        <parameter>
          <name>outputDirectory</name>
          <type>java.io.File</type>
          <required>true</required>
          <editable>false</editable>
          <description></description>
        </parameter>
`

Supposedly not editable, but changing the value in the pom.xml does change where the plugin writes files.  However, it appears that when I remove the configuration all together the default location for the files is the same as what is being configured (${project.build.directory}/classes) so I was able to safely fix the error by simply removing the config.

**Comment by rombert** [comment]
With the latest version of the `maven-scr-plugin` I am able to simply remove the configuration block altogether and the files are generated in the right location.

```
.
├── com
│   └── example
│       └── core
│           ├── filters
│           │   └── LoggingFilter.class
│           ├── listeners
│           │   └── SimpleResourceListener.class
│           ├── models
│           │   └── HelloWorldModel.class
│           ├── package-info.class
│           ├── schedulers
│           │   └── SimpleScheduledTask.class
│           └── servlets
│               └── SimpleServlet.class
├── META-INF
│   └── MANIFEST.MF
└── OSGI-INF
    ├── com.example.core.filters.LoggingFilter.xml
    ├── com.example.core.listeners.SimpleResourceListener.xml
    ├── com.example.core.schedulers.SimpleScheduledTask.xml
    ├── com.example.core.servlets.SimpleServlet.xml
    └── metatype
        ├── com.example.core.schedulers.SimpleScheduledTask.properties
        └── com.example.core.schedulers.SimpleScheduledTask.xml
```
