### ISSUE TITLE
OSGi bundle not getting uninstalled in case un-installation is done after new version installation of AEM package 

### ISSUE THREAD

**Issue by sandeepkumar03** [Adobe-Marketing-Cloud/aem-project-archetype#62]
When we are overwriting a new package with new version, on un-installation the OSGi bundle is not getting removed from web console. Following are the steps to reproduce.
1. Create a new multimodule project from AEM Plugin
2. Build and deploy to AEM instance in Package Manager. (OSGi console shows bundle with version A)
3. Change the version of project created in step 1 to something different say B.
4. Build and deploy to AEM instance in Package Manager (OSGi console shows bundle with version B)
5. Uninstall the AEM package from Package Manager.
6. Notice that OSGi console still shows bundle with version B. It should be version A.

Also refer [issue raised on AEM Plugin Page](https://github.com/Adobe-Marketing-Cloud/aem-eclipse-developer-tools/issues/68). This has some analysis done on this issue.

From the [archetypes list](https://repo.adobe.com/nexus/content/groups/public/archetype-catalog.xml) 

Following works fine 

```
<groupId>com.day.jcr.vault</groupId>
<artifactId>multimodule-content-package-archetype</artifactId>
```

While  following does not

```
<groupId>com.adobe.granite.archetypes</groupId>
<artifactId>aem-project-archetype</artifactId>
```

The `aem-project-archetype` generates extra exclude pattern

```
<filter root="/apps/myapp">
    <exclude pattern="/apps/myapp/install" />
</filter>
```

This exclude pattern is not present in the `multimodule-content-package-archetype`

Did few tests, after we remove this from filter, the `aem-project-archetype` works fine, not sure if there would be any side-effects due to this.

**Comment by pmminov** [comment]
@sandeepkumar03 hey, not sure if it is related, but I'm not able to deploy a new core bundle at all. Is like no uninstallation is happening at all.

Whenever I run mvn clean install -PautoInstallPackage on my project the core bundle jar will not have any changes. I have to jump into CRXDE and manually delete the jar

I tried changing the filter.xml as you suggested but no results

**Comment by sandeepkumar03** [comment]
I think bundle not getting installed at all would be a different issue. Just check if the build is created properly.  Do you  bundle inside see apps/<app_name>/install in the package?

Also there is a [bug in Sling](https://issues.apache.org/jira/browse/SLING-5421) where the OSGi bundle is not installed due to "/system/sling/installer/jcr/pauseInstallation" node. 

See if this node is there in your AEM instance. [Try deleting](http://help-forums.adobe.com/content/adobeforums/en/experience-manager-forum/adobe-experience-manager.topic.html/forum__7gqa-i_have_my_bundlejar.html) the node and see if bundle gets installed.

There is hot fix for this issue which you can get from Adobe Day Care.

**Comment by kwin** [comment]
I also think that the filter rule in https://github.com/Adobe-Marketing-Cloud/aem-project-archetype/blob/master/src/main/archetype/ui.apps/src/main/content/META-INF/vault/filter.xml#L4 should be adjusted to not exclude anything. Otherwise bundle deployment might not work as expected.
