### ISSUE TITLE
Include best practice for clientlib CSS support files

### ISSUE THREAD

**Issue by pmminov** [Adobe-Marketing-Cloud/aem-project-archetype#63]
Hi, just a small request, as there is no easy consensus on how clientlibs work. And probably this archetype would be the best way to provide best practice

It is suggested to use Component-Level clientlibs, these are all grouped up by a clientlib at the /etc/design level, which guarantees they are not being exposed from the /apps level

However, this gets a bit blurry when there are images or fonts involved. If lets say component A has the following CSS rule

.bg {
  background-image: url(../img/cloud-img.png);}

That resolves to 

background-image: url(../../../apps/my-project/components/content/componentA/clientlib/img/cloud-img.png);

despite of the clientlib being offered via /etc/clientlib-all

Whats your take on this case? 

Could you add an image folder to the archetype and provide a nice read-me suggesting best practice?

**Comment by jamiecounsell** [comment]
@pmminov images should not be stored with your clientlibs. They should be stored in etc/designs.

**Comment by bpauli** [comment]
@pmminov With the latest AEM 6.3 release you also have the possibility to serve a clientlib via a proxy servlet, which bypasses the ACL restrictions. You can also access static resources like images and fonts, if they are located in a `resources` subdirectory.
For more information please have a look to the related documentation at https://adobe.ly/2fOb5Tl
