### ISSUE TITLE
Core bundle does not resolve on AEM 6.3 due to different version of javax.inject

### ISSUE THREAD

**Issue by ksurendra** [Adobe-Marketing-Cloud/aem-project-archetype#68]
With AEM 6.3 the same error as posted/closed here [ https://github.com/Adobe-Marketing-Cloud/aem-project-archetype/issues/59 ] shows up.

Core bundle is not resolved with wrong version of javax.inject

![screen shot 2016-11-28 at 4 20 21 pm](https://cloud.githubusercontent.com/assets/902972/20689072/35e4eb6e-b589-11e6-85af-d8e1b2c6d406.png)

**Comment by rombert** [comment]
Thanks for the report. This has been fixed in the development version - see #59
