### ISSUE TITLE
Maven compiler plugin config defaults to Java 6

### ISSUE THREAD

**Issue by toniedzwiedz** [Adobe-Marketing-Cloud/aem-project-archetype#69]
Upon generating a project based on this archetype, the `maven-compiler-plugin` configuration in the resulting `pom.xml` defaults to Java 6

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.6</source>
                    <target>1.6</target>
                </configuration>
            </plugin>

Whereas the currently [supported versions of AEM require Java 7 or higher](https://docs.adobe.com/content/docs/en/aem/6-0/deploy/technical-requirements.html#Java%20Virtual%20Machines). It seems reasonable to me that the defaults to be changed to 1.7 or perhaps 1.8 (given how Oracle Java 7 reached end of life as of May 2015) in terms of both source and binaries.

Is there a reason to keep these defaults lower?

**Comment by rombert** [comment]
1.8 sounds like a good idea. It's supported by 6.0 SP1 or higher.

Would you be able to submit a pull request with this change?

**Comment by toniedzwiedz** [comment]
> Would you be able to submit a pull request with this change?

@rombert I'd be happy to.

**Comment by rombert** [comment]
@toniedzwiedz  - great, looking forward to that!
