### ISSUE TITLE
Integration Tests break AEM server

### ISSUE THREAD

**Issue by sschwedler** [Adobe-Marketing-Cloud/aem-project-archetype#70]
When running integration tests the AEM package manager does not work anymore. It's because task installs old versions of httpclient-osgi and httpscore-osgi. As a workaround the pom.xml in launcher project can be modified by commenting the bundles. Integration tests work without installing these bundles.

 <sling.additional.bundle.7>httpclient-osgi</sling.additional.bundle.7>
<sling.additional.bundle.8>httpcore-osgi</sling.additional.bundle.8>

**Comment by rombert** [comment]
Thanks for the report @sschwedler . Can you try setting the bundle versions equal to the ones in AEM?

**Comment by rombert** [comment]
Also, what version of AEM did you test this with?

**Comment by sschwedler** [comment]
AEM 6.2. and AEM 6.2. SP1

**Comment by sschwedler** [comment]
When changing the versions tag of the dependencies for httpclient and httpcore I get the following message when executing the integration test.

[main] INFO org.apache.sling.testing.tools.sling.BundlesInstaller - Not reinstalling: org.apache.httpcomponents.httpclient
[main] INFO org.apache.sling.testing.tools.sling.BundlesInstaller - Not reinstalling: org.apache.httpcomponents.httpcore

**Comment by rombert** [comment]
That sounds promising. Does the package manager break with these updated versions? If not, what versions did you change them to?

BTW, if you have something that works for you and you have the time to do so, feel free to create a pull request.

**Comment by sschwedler** [comment]
With that the package manager works fine after an integration test. The question to me is, why does it install these bundles which are already available in AEM?

**Comment by rombert** [comment]
My guess would be that older AEM versions are using http client version 3, but I have to check first.
