### ISSUE TITLE
archetypes nexus repo hasn't been updated for almost two years

### ISSUE THREAD

**Issue by ArashNamics** [Adobe-Marketing-Cloud/aem-project-archetype#75]
Check out:
https://repo.adobe.com/nexus/content/groups/public/com/adobe/granite/archetypes/aem-project-archetype/

As a result, you get an almost two years old version of aem archetypes if you use following command:
`mvn archetype:generate \
 -DarchetypeGroupId=com.adobe.granite.archetypes \
 -DarchetypeArtifactId=aem-project-archetype \
 -DarchetypeVersion=10 \
 -DarchetypeRepository=https://repo.adobe.com/nexus/content/groups/public/`

**Comment by MaartenTutak** [comment]
+1

**Comment by rombert** [comment]
Well, there hasn't been an update that we released so there is no error here :-) Is there anything in particular that  you are missing?
