### ISSUE TITLE
README Usage section: mvn command fail for setup

### ISSUE THREAD

**Issue by lscmaro** [Adobe-Marketing-Cloud/aem-project-archetype#76]
Starting by creating a new empty folder on a new Windows machine, with newest maven added, 3.3.9.  
In the usage section of the readme stating the mvn command to run, After removal of '/' , (which doesn't work on windows consoles) I ran this:

`mvn archetype:generate -DarchetypeGroupId=com.adobe.granite.archetypes
 -DarchetypeArtifactId=aem-project-archetype -DarchetypeVersion=10 
 -DarchetypeRepository=https://repo.adobe.com/nexus/content/groups/public/`
(^^This may look malformed but it is not malformed in the console just in this issue^^)

This still fails with errors as: 

`[WARNING] Archetype not found in any catalog. Falling back to central repository
 (http://repo.maven.apache.org/maven2).`

Even though the `-DarchetypeRepository` parameter is supplied, the build defaults back to maven2 repo looking for files, which then tries to gather POM & JAR file that do not exist.

`[WARNING] Use -DarchetypeRepository=<your repository> if archetype's repository
is elsewhere.`

`Downloading: http://repo.maven.apache.org/maven2/com/adobe/granite/archetypes/ae
m-project-archetype/10/aem-project-archetype-10.pom
[WARNING] The POM for com.adobe.granite.archetypes:aem-project-archetype:jar:10
is missing, no dependency information available
Downloading: http://repo.maven.apache.org/maven2/com/adobe/granite/archetypes/ae
m-project-archetype/10/aem-project-archetype-10.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------`

Makes no sense. OS: Windows 7;Maven: 3.39 & 3.2.1 tried; Tried on a MacBook machine that has no issues installing this and on same network. Multiple Windows machines tried.

**Comment by rombert** [comment]
Can you access https://repo.adobe.com/nexus/content/groups/public/ in the browser?
Also, can you attach the log running the maven command with the {{-X}} argument?

**Comment by lscmaro** [comment]
Yes. I can access both URLs in the browser:
[https://repo.adobe.com/nexus/content/groups/public/](url)
[https://repo.maven.apache.org/maven2/](url)

I finially got some success with this after digging, and now have the info in my local mvn repository, so it doesn't fail. I went and changed the central repository location in the maven settings.xml to:

`<mirrors>

    <mirror>

      <id>google-maven-central</id>

      <name>Google Maven Central</name>

      <url>https://maven-central.storage.googleapis.com</url>

      <mirrorOf>central</mirrorOf>

    </mirror> 

</mirrors>`

running mvn after this, passed with no 404s when fetching archetype dependencies.
I'm sure I can delete my local .m2 repository and attempted this again, it would result in a failure.

but I did get a some of log from the other windows machine, which is fairly long,
again this is a newly configured machine with maven so there was no local repository: 


'[DEBUG]   Included: asm:asm-tree:jar:3.2
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:3.0.21
[DEBUG]   Included: org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-6

[DEBUG]   Included: org.sonatype.sisu:sisu-inject-bean:jar:1.4.2
[DEBUG]   Included: org.sonatype.sisu:sisu-guice:jar:noaop:2.1.7
[DEBUG]   Included: org.sonatype.aether:aether-util:jar:1.7
[DEBUG]   Included: org.codehaus.plexus:plexus-interpolation:jar:1.14
[DEBUG]   Included: org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3
[DEBUG]   Included: org.sonatype.plexus:plexus-cipher:jar:1.4
[DEBUG]   Included: org.apache.maven.shared:maven-invoker:jar:2.2
[DEBUG]   Included: org.apache.maven.shared:maven-artifact-transfer:jar:0.9.0
[DEBUG]   Included: org.apache.maven.shared:maven-common-artifact-filters:jar:3.
0.0
[DEBUG]   Included: org.apache.maven.shared:maven-shared-utils:jar:3.0.0
[DEBUG]   Included: com.google.code.findbugs:jsr305:jar:2.0.1
[DEBUG]   Included: commons-codec:commons-codec:jar:1.6
[DEBUG]   Included: commons-collections:commons-collections:jar:3.2.1
[DEBUG]   Included: org.apache.maven.shared:maven-script-interpreter:jar:1.0
[DEBUG]   Included: org.beanshell:bsh:jar:2.0b4
[DEBUG]   Included: org.apache.ant:ant:jar:1.8.1
[DEBUG] Configuring mojo org.apache.maven.plugins:maven-archetype-plugin:3.0.0:g
enerate from plugin realm ClassRealm[plugin>org.apache.maven.plugins:maven-arche
type-plugin:3.0.0, parent: sun.misc.Launcher$AppClassLoader@1f96302]
[DEBUG] Setting property: classpath.resource.loader.class => 'org.codehaus.plexu
s.velocity.ContextClassLoaderResourceLoader'.
[DEBUG] Setting property: site.resource.loader.class => 'org.codehaus.plexus.vel
ocity.SiteResourceLoader'.
[DEBUG] Setting property: velocimacro.messages.on => 'false'.
[DEBUG] Setting property: resource.loader => 'classpath,site'.
[DEBUG] Setting property: runtime.log.invalid.references => 'false'.
[DEBUG] Setting property: resource.manager.logwhenfound => 'false'.
[DEBUG] Initializing Velocity, Calling init()...
[DEBUG] *******************************************************************
[DEBUG] Starting Apache Velocity v1.7 (compiled: 2010-11-19 12:14:37)
[DEBUG] RuntimeInstance initializing.
[DEBUG] Default Properties File: org\apache\velocity\runtime\defaults\velocity.p
roperties
[DEBUG] LogSystem has been deprecated. Please use a LogChute implementation.
[DEBUG] Default ResourceManager initializing. (class org.apache.velocity.runtime
.resource.ResourceManagerImpl)
[DEBUG] ResourceLoader instantiated: org.codehaus.plexus.velocity.ContextClassLo
aderResourceLoader
[DEBUG] ResourceLoader instantiated: org.codehaus.plexus.velocity.SiteResourceLo
ader
[DEBUG] ResourceCache: initialized (class org.apache.velocity.runtime.resource.R
esourceCacheImpl) with class java.util.Collections$SynchronizedMap cache map.
[DEBUG] Default ResourceManager initialization complete.
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Stop
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Define
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Break
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Evaluate
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Literal
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Macro
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Parse
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Include
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Foreach
[DEBUG] Created '20' parsers.
[DEBUG] Velocimacro : initialization starting.
[DEBUG] Velocimacro : allowInline = true : VMs can be defined inline in template
s
[DEBUG] Velocimacro : allowInlineToOverride = false : VMs defined inline may NOT
 replace previous VM definitions
[DEBUG] Velocimacro : allowInlineLocal = false : VMs defined inline will be glob
al in scope if allowed.
[DEBUG] Velocimacro : autoload off : VM system will not automatically reload glo
bal library macros
[DEBUG] Velocimacro : Velocimacro : initialization complete.
[DEBUG] RuntimeInstance successfully initialized.
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-archetype-plugin:3.0.0:
generate' with basic configurator -->
[DEBUG]   (f) archetypeArtifactId = aem-project-archetype
[DEBUG]   (f) archetypeCatalog = remote,local
[DEBUG]   (f) archetypeGroupId = com.adobe.granite.archetypes
[DEBUG]   (f) archetypeVersion = 10
[DEBUG]   (f) basedir = C:\testlou
[DEBUG]   (f) interactiveMode = true
[DEBUG]   (f) localRepository =       id: local
      url: file:///C:/Users/my.repo2/.m2/repository/
   layout: default
snapshots: [enabled => true, update => always]
 releases: [enabled => true, update => always]

[DEBUG]   (f) remoteArtifactRepositories = [      id: central
      url: https://repo.maven.apache.org/maven2
   layout: default
snapshots: [enabled => false, update => daily]
 releases: [enabled => true, update => daily]
]
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@6fc505
[DEBUG] -- end configuration --
[INFO] Generating project in Interactive mode
[DEBUG] Searching for remote catalog: https://repo.maven.apache.org/maven2/arche
type-catalog.xml
[DEBUG] Using catalog C:\Users\my.repo2\.m2\repository\archetype-catalog.xml

[WARNING] Archetype not found in any catalog. Falling back to central repository
 (http://repo.maven.apache.org/maven2).
[WARNING] Use -DarchetypeRepository=<your repository> if archetype's repository
is elsewhere.
[DEBUG] Not found archetype com.adobe.granite.archetypes:aem-project-archetype:1
0 in cache
[DEBUG] Using transporter WagonTransporter with priority -1.0 for http://repo.ma
ven.apache.org/maven2
[DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for http://re
po.maven.apache.org/maven2
Downloading: http://repo.maven.apache.org/maven2/com/adobe/granite/archetypes/ae
m-project-archetype/10/aem-project-archetype-10.pom
[DEBUG] Writing tracking file C:\Users\my.repo2\.m2\repository\com\adobe\gra
nite\archetypes\aem-project-archetype\10\aem-project-archetype-10.pom.lastUpdate
d
[DEBUG] Using transporter WagonTransporter with priority -1.0 for https://repo.m
aven.apache.org/maven2
[DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for https://r
epo.maven.apache.org/maven2
Downloading: https://repo.maven.apache.org/maven2/com/adobe/granite/archetypes/a
em-project-archetype/10/aem-project-archetype-10.pom
[DEBUG] Writing tracking file C:\Users\my.repo2\.m2\repository\com\adobe\gra
nite\archetypes\aem-project-archetype\10\aem-project-archetype-10.pom.lastUpdate
d
[WARNING] The POM for com.adobe.granite.archetypes:aem-project-archetype:jar:10
is missing, no dependency information available
[DEBUG] Using transporter WagonTransporter with priority -1.0 for http://repo.ma
ven.apache.org/maven2
[DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for http://re
po.maven.apache.org/maven2
Downloading: http://repo.maven.apache.org/maven2/com/adobe/granite/archetypes/ae
m-project-archetype/10/aem-project-archetype-10.jar
[DEBUG] Writing tracking file C:\Users\my.repo2\.m2\repository\com\adobe\gra
nite\archetypes\aem-project-archetype\10\aem-project-archetype-10.jar.lastUpdate
d
[DEBUG] Using transporter WagonTransporter with priority -1.0 for https://repo.m
aven.apache.org/maven2
[DEBUG] Using connector BasicRepositoryConnector with priority 0.0 for https://r
epo.maven.apache.org/maven2
Downloading: https://repo.maven.apache.org/maven2/com/adobe/granite/archetypes/a
em-project-archetype/10/aem-project-archetype-10.jar
[DEBUG] Writing tracking file C:\Users\my.repo2\.m2\repository\com\adobe\gra
nite\archetypes\aem-project-archetype\10\aem-project-archetype-10.jar.lastUpdate
d
[DEBUG] Archetype com.adobe.granite.archetypes:aem-project-archetype:10 doesn't
exist
org.apache.maven.archetype.downloader.DownloadException: Error downloading com.a
dobe.granite.archetypes:aem-project-archetype:jar:10.
        at org.apache.maven.archetype.downloader.DefaultDownloader.download(Defa
ultDownloader.java:83)
        at org.apache.maven.archetype.common.DefaultArchetypeArtifactManager.exi
sts(DefaultArchetypeArtifactManager.java:279)
        at org.apache.maven.archetype.ui.generation.DefaultArchetypeGenerationCo
nfigurator.configureArchetype(DefaultArchetypeGenerationConfigurator.java:121)
        at org.apache.maven.archetype.mojos.CreateProjectFromArchetypeMojo.execu
te(CreateProjectFromArchetypeMojo.java:185)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: org.apache.maven.shared.artifact.resolve.ArtifactResolverException: C
ould not find artifact com.adobe.granite.archetypes:aem-project-archetype:jar:10
 in aem-project-archetype-repo (http://repo.maven.apache.org/maven2)
        at org.apache.maven.shared.artifact.resolve.internal.Maven31ArtifactReso
lver.resolveArtifact(Maven31ArtifactResolver.java:116)
        at org.apache.maven.shared.artifact.resolve.internal.Maven31ArtifactReso
lver.resolveArtifact(Maven31ArtifactResolver.java:80)
        at org.apache.maven.shared.artifact.resolve.internal.DefaultArtifactReso
lver.resolveArtifact(DefaultArtifactResolver.java:73)
        at org.apache.maven.archetype.downloader.DefaultDownloader.download(Defa
ultDownloader.java:79)
        ... 25 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not
find artifact com.adobe.granite.archetypes:aem-project-archetype:jar:10 in aem-p
roject-archetype-repo (http://repo.maven.apache.org/maven2)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(Defa
ultArtifactResolver.java:444)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtif
acts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtif
act(DefaultArtifactResolver.java:223)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtif
act(DefaultRepositorySystem.java:294)
        at org.apache.maven.shared.artifact.resolve.internal.Maven31ArtifactReso
lver.resolveArtifact(Maven31ArtifactResolver.java:108)
        ... 28 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find
 artifact com.adobe.granite.archetypes:aem-project-archetype:jar:10 in aem-proje
ct-archetype-repo (http://repo.maven.apache.org/maven2)
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transfer
Failed(ArtifactTransportListener.java:39)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunne
r.run(BasicRepositoryConnector.java:355)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(Runn
ableErrorForwarder.java:67)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExe
cutor.execute(BasicRepositoryConnector.java:581)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(Basic
RepositoryConnector.java:249)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownl
oads(DefaultArtifactResolver.java:520)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(Defa
ultArtifactResolver.java:421)
        ... 32 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.478 s
[INFO] Finished at: 2017-02-24T10:36:39-05:00
[INFO] Final Memory: 11M/48M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3
.0.0:generate (default-cli) on project standalone-pom: The desired archetype doe
s not exist (com.adobe.granite.archetypes:aem-project-archetype:10) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal o
rg.apache.maven.plugins:maven-archetype-plugin:3.0.0:generate (default-cli) on p
roject standalone-pom: The desired archetype does not exist (com.adobe.granite.a
rchetypes:aem-project-archetype:10)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: org.apache.maven.plugin.MojoFailureException: The desired archetype d
oes not exist (com.adobe.granite.archetypes:aem-project-archetype:10)
        at org.apache.maven.archetype.mojos.CreateProjectFromArchetypeMojo.execu
te(CreateProjectFromArchetypeMojo.java:201)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:207)
        ... 20 more
Caused by: org.apache.maven.archetype.exception.UnknownArchetype: The desired ar
chetype does not exist (com.adobe.granite.archetypes:aem-project-archetype:10)
        at org.apache.maven.archetype.ui.generation.DefaultArchetypeGenerationCo
nfigurator.configureArchetype(DefaultArchetypeGenerationConfigurator.java:125)
        at org.apache.maven.archetype.mojos.CreateProjectFromArchetypeMojo.execu
te(CreateProjectFromArchetypeMojo.java:185)
        ... 22 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption

C:\test>'

**Comment by rombert** [comment]
I think I know what's going on. It seems that the 3.0.0 version of the maven-archetype-plugin contains a regression. Can you try replacing `mvn archetype:generate` with `mvn org.apache.maven.plugins:maven-archetype-plugin:2.4:generate` in the command line?

**Comment by rombert** [comment]
Note that you should also use `-DarchetypeCatalog` instead of `-DarchetypeRepository`

**Comment by lscmaro** [comment]
Works as expected with old version. Thanks for the advice and great find! Hopefully 3.0.1 is the one :+1:

**Comment by rombert** [comment]
Great to hear that it works. 

We will probably keep referencing the old plugin version as the developers are not interested in restoring the old behaviour, but for 3.0.1 they will throw an error when we pass an invalid archetype catalog.
