### ISSUE TITLE
Archetype version 11 not found

### ISSUE THREAD

**Issue by Jdruwe** [Adobe-Marketing-Cloud/aem-project-archetype#86]
When I run the following command:

`mvn org.apache.maven.plugins:maven-archetype-plugin:2.4:generate \
 -DarchetypeGroupId=com.adobe.granite.archetypes \
 -DarchetypeArtifactId=aem-project-archetype \
 -DarchetypeVersion=11 \
 -DarchetypeCatalog=https://repo.adobe.com/nexus/content/groups/public/`

I get this error:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.4:generate (default-cli) on project standalone-pom: The desired archetype does not exist (com.adobe.granite.archetypes:aem-project-archetype:11) -> [Help 1]`

But the docs clearly state: version 11 --> 6.2 or newer

**Comment by rombert** [comment]
That's because version 11 is not out yet :-) The usage instructions point you to version 10. Once 11 is out, you'll be able to use that as well.

**Comment by Jdruwe** [comment]
Any idea when version 11 will be out? :)

**Comment by rombert** [comment]
Probably once #84 is done.
