### ISSUE TITLE
Support for Apache Felix SCR Plugin

### ISSUE THREAD

**Issue by LouisNguenkam** [Adobe-Marketing-Cloud/aem-project-archetype#91]
Hi,

It looks like the Apache Felix SCR Plugin is not integrated to the POM generated by the archetype version 11. 
After generating a new project with using this archetype and creating some simple services using the felix src annotations, those services were not registered in the felix container. However, the default services provided OOTB as OSGI services were always registered. 
* Does this mean that OSGI  is the prefered way / best practice for service declaration suggested by Adobe? 
* Do OSGI service delaration have some advantages over Apache Felix SCR? 
* Or do I simply have some wrong configurations in my project setup?

**Comment by bpauli** [comment]
@LouisNguenkam Please have a look to the official Felix Maven SCR page at [0].

> Note: While the Apache Felix Maven SCR Plugin is a great tool (see below), for developing OSGi components using Declarative Services you should use the official annotations from the OSGi R6 specification. The development of the Apache Felix SCR Plugin is in maintenance mode.

The official annotations from the OSGi R6 specification are now recommended for service declaration. Although, the Felix Maven SCR plugin is still supported by the latest version of AEM (6.3) and there is no need to update existing code. However if you want to use the new features (like metatype generation) you have to switch to the official OSGi R6 annotations [1].

[0] http://felix.apache.org/documentation/subprojects/apache-felix-maven-scr-plugin.html
[1] https://blog.osoco.de/2015/11/osgi-components-simply-simple-part-iii/

**Comment by LouisNguenkam** [comment]
Cool,

Thanks for pointing this out.

Cheers
Louis
