### ISSUE TITLE
Ranking property must be of type Integer

### ISSUE THREAD

**Issue by heervisscher** [Adobe-Marketing-Cloud/aem-project-archetype#93]
The ranking property is now of the type String, must be of type Integer. This is used on the Filter-class.

Example:
@Component(service = Filter.class,
           property = {
                   Constants.SERVICE_DESCRIPTION + "=Demo to filter incoming requests",
                   EngineConstants.SLING_FILTER_SCOPE + "=" + EngineConstants.FILTER_SCOPE_REQUEST,
                   Constants.SERVICE_RANKING + "=-700"

           })

Example on the correct usage of the ranking property: https://github.com/heervisscher/htl-examples/blob/master/core/src/main/java/com/adobe/examples/htl/core/bindings/CustomBindingProvider.java

**Comment by bpauli** [comment]
Hi @heervisscher, 

Thanks for reporting this. Will be fixed when #90 is merged.

**Comment by heervisscher** [comment]
thanks!
