### ISSUE TITLE
Issues with archetype 11 / AEM 6.3

### ISSUE THREAD

**Issue by ttaveira** [Adobe-Marketing-Cloud/aem-project-archetype#94]
Hi,

I'm having some issues with archetype 11. Through the command line I created my local project with:
`mvn org.apache.maven.plugins:maven-archetype-plugin:2.4:generate -DarchetypeGroupId=com.adobe.granite.archetypes -DarchetypeArtifactId=aem-project-archetype -DarchetypeVersion=11 -DarchetypeCatalog=https://repo.adobe.com/nexus/content/groups/public/`

After that, I tried to deploy the project to AEM with:
`mvn clean install -PautoInstallPackage`

This results in the following error:
`[INFO] Scanning for projects...
[WARNING] The POM for com.day.jcr.vault:content-package-maven-plugin:jar:0.5.1 is missing, no dependency information available
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin com.day.jcr.vault:content-package-maven-plugin:0.5.1 or one of its dependencies could not be resolved: Failure to find com.day.jcr.vault:content-package-maven-plugin:jar:0.5.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @
[ERROR] Unknown packaging: content-package @ org.deloittedigital:testproject.ui.apps:[unknown-version], C:\Users\ttaveira\workspace\testproject\ui.apps\pom.xml, line 34, column 16
[ERROR] Unresolveable build extension: Plugin com.day.jcr.vault:content-package-maven-plugin:0.5.1 or one of its dependencies could not be resolved: Failure to find com.day.jcr.vault:content-package-maven-plugin:jar:0.5.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced @
[ERROR] Unknown packaging: content-package @ org.deloittedigital:testproject.ui.content:[unknown-version], C:\Users\ttaveira\workspace\testproject\ui.content\pom.xml, line 34, column 16`

I'm using Maven 3.5.0 with Java 1.8.0_131.

Any idea what might be wrong?

Thank you,
Tiago

**Comment by Hawleywood** [comment]
Add `-Padobe-public` to the mvn command

**Comment by jamiecounsell** [comment]
@ttaveira  You also may need to update your `settings.xml` as described in [this article](https://helpx.adobe.com/experience-manager/using/first-osgi.html).

**Comment by wiiitek** [comment]
I have added some updates for the archetype to make it work for AEM 6.3.0.
See https://github.com/Adobe-Marketing-Cloud/aem-project-archetype/pull/101.

**Comment by bpauli** [comment]
fixed in #101

**Comment by timdonovanuk** [comment]
I see the fix is merged but I get the same error when following https://github.com/Adobe-Marketing-Cloud/aem-project-archetype

**Comment by wiiitek** [comment]
What is the error you get? Are you executing the command in single line?:

```
mvn org.apache.maven.plugins:maven-archetype-plugin:2.4:generate -DarchetypeGroupId=com.adobe.granite.archetypes -DarchetypeArtifactId=aem-project-archetype -DarchetypeVersion=12 -DarchetypeCatalog=https://repo.adobe.com/nexus/content/groups/public/
```

It works for me on Windows 8.1 with Maven 3.3.9 and Oracle java 1.8 ...

**Comment by timdonovanuk** [comment]
@wiiitek As mentioned by the original poster, it is not a problem executing the mvn generate command, it's a problem doing mvn clean install after. 

java version "1.8.0_144"
maven 3.5.0

**Comment by devinyan** [comment]
@ttaveira  Hi ,did you fix it yet? I met the same issue with you.

**Comment by mukul24** [comment]
Use below command to deploy the package to your AEM server:
**mvn -PautoInstallPackage -Padobe-public clean install**

It is working for me.

**Comment by godanny86** [comment]
@devinyan have you updated your .m2/settings.xml file to include a reference to the Adobe Nexus repo? You can follow this article to add the adobe-public profile: https://helpx.adobe.com/experience-manager/kb/SetUpTheAdobeMavenRepository.html

**Comment by nithyanairkh** [comment]
mvn -PautoInstallPackage -Padobe-public clean install worked to solve the issue with Archetype13, AEM6.4
