### ISSUE TITLE
Update the annotations

### ISSUE THREAD

**Issue by sasconsul** [Adobe-Marketing-Cloud/aem-project-archetype#96]
I noticed that SimpleServlet.java uses deprecated  @Component annotation.

**Comment by rombert** [comment]
@sasconsul  - thanks for the report. Could you send a pull request with a fix?

**Comment by bpauli** [comment]
@sasconsul, what version of the archetype did you use while creating the project? In the latest released version (v11) the SimpleServlet uses the OSGi R6 component annotation - which is up to date.
