### ISSUE TITLE
autoInstallPackage not installing core bundle

### ISSUE THREAD

**Issue by mkovacek** [Adobe-Marketing-Cloud/aem-project-archetype#97]
I have created AEM project using archtype 11 and problem is when I run mvn clean install -PautoInstallPackage, adobe-public core bundle is not installed, only apps and content

**Comment by bpauli** [comment]
Hi @mkovacek ,

I'm not able to reproduce this issue. The core bundle should be installed together with the ui.apps content package. Can you please share your maven output of the build?

Moreover it would be useful if you can share your build environment and AEM target version. Thanks!

**Comment by mkovacek** [comment]
Hi @bpauli, 
Maven 3.5.0, Java 1.8.0_131.
Windows 10
https://gist.github.com/mkovacek/295aea00111c30f43a96916635c28a49

Build is successfull but bundle is not installed, jar exists in /apps/com/dcep/microsites/ppfi/install

**Comment by mkovacek** [comment]
Problem was in ui.apps pom.xml

When you embedding core bundle in vault package plugin, then in target you shouldn't have more then 3 levels under apps to save bundle jar file. 

# For example:

**- Working:**

1. <target>/apps/my-project/install</target>
2. <target>/apps/com/my-project/install</target>

**- Not working:**

1. <target>/apps/com/my-project/sub-project/install</target>

# Code:
           <plugin>
                <groupId>com.day.jcr.vault</groupId>
                <artifactId>content-package-maven-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <filterSource>src/main/content/META-INF/vault/filter.xml</filterSource>
                    <verbose>true</verbose>
                    <failOnError>true</failOnError>
                    <group>my-project</group>
                    <embeddeds>
                        <embedded>
                            <groupId>com.org.sites.projectname</groupId>
                            <artifactId>my-project.core</artifactId>
                            <target>/apps/my-project/sub-project/install</target>
                        </embedded>
                    </embeddeds>
                </configuration>
            </plugin>
```

**Comment by agrajm** [comment]
For anyone else reading this, the Max hierarchy depth of install folders is driven by an OSGi config - http://localhost:4502/system/console/configMgr/org.apache.sling.installer.provider.jcr.impl.JcrInstaller @mkovacek Try changing the default value to 5/6 whatever suits you and then the bundles should be installed

**Comment by mkovacek** [comment]
@agrajm Yea I found that later, but thx 👍
